[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bank_of_sol = "5Xi2uL4MB1RDnDPFHEiec6beWxFqyzFhgYpd2ACjr17m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/levi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
